//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosaic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mosaic.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Aboutbox {
            get {
                return ResourceManager.GetString("Aboutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least you have to add 15 tiles..
        /// </summary>
        internal static string AddAtLeast15Tiles {
            get {
                return ResourceManager.GetString("AddAtLeast15Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to add some tiles first..
        /// </summary>
        internal static string AddTilesFirst {
            get {
                return ResourceManager.GetString("AddTilesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust tile hue.
        /// </summary>
        internal static string AdjustHue {
            get {
                return ResourceManager.GetString("AdjustHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging Master Bitmap....
        /// </summary>
        internal static string AveragingMasterBitmap {
            get {
                return ResourceManager.GetString("AveragingMasterBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m calculating mosaic. This may take a while....
        /// </summary>
        internal static string CalculateMosaic {
            get {
                return ResourceManager.GetString("CalculateMosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors calculated..
        /// </summary>
        internal static string ColorsCalculated {
            get {
                return ResourceManager.GetString("ColorsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and Resizing Tile Images....
        /// </summary>
        internal static string LoadingAndResizingTiles {
            get {
                return ResourceManager.GetString("LoadingAndResizingTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maser file....
        /// </summary>
        internal static string LoadingMasterFile {
            get {
                return ResourceManager.GetString("LoadingMasterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master image.
        /// </summary>
        internal static string MasterImage {
            get {
                return ResourceManager.GetString("MasterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic.
        /// </summary>
        internal static string Mosaic {
            get {
                return ResourceManager.GetString("Mosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save picture.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
