//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosaicApplication {
    using System;


    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }

        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MosaicApplication.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About.
        /// </summary>
        public static string Aboutbox {
            get {
                return ResourceManager.GetString("Aboutbox", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu At least you have to add 15 tiles..
        /// </summary>
        public static string AddAtLeast15Tiles {
            get {
                return ResourceManager.GetString("AddAtLeast15Tiles", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add hue to each tile.
        /// </summary>
        public static string AddHue {
            get {
                return ResourceManager.GetString("AddHue", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have to add some tiles first..
        /// </summary>
        public static string AddTilesFirst {
            get {
                return ResourceManager.GetString("AddTilesFirst", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adjust tile hue.
        /// </summary>
        public static string AdjustHue {
            get {
                return ResourceManager.GetString("AdjustHue", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Averaging Master Bitmap....
        /// </summary>
        public static string AveragingMasterBitmap {
            get {
                return ResourceManager.GetString("AveragingMasterBitmap", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bitmap.
        /// </summary>
        public static string Bitmap {
            get {
                return ResourceManager.GetString("Bitmap", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Buffer.
        /// </summary>
        public static string Buffer {
            get {
                return ResourceManager.GetString("Buffer", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu I&apos;m calculating mosaic. This may take a while....
        /// </summary>
        public static string CalculateMosaic {
            get {
                return ResourceManager.GetString("CalculateMosaic", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color tiles.
        /// </summary>
        public static string ColorPlacedTiles {
            get {
                return ResourceManager.GetString("ColorPlacedTiles", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Colors calculated..
        /// </summary>
        public static string ColorsCalculated {
            get {
                return ResourceManager.GetString("ColorsCalculated", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contrast.
        /// </summary>
        public static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Directory does not exist..
        /// </summary>
        public static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Done!.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GIF image.
        /// </summary>
        public static string GIFPicture {
            get {
                return ResourceManager.GetString("GIFPicture", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading and Resizing Tile Images....
        /// </summary>
        public static string LoadingAndResizingTiles {
            get {
                return ResourceManager.GetString("LoadingAndResizingTiles", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading maser file....
        /// </summary>
        public static string LoadingMasterFile {
            get {
                return ResourceManager.GetString("LoadingMasterFile", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Master image.
        /// </summary>
        public static string MasterImage {
            get {
                return ResourceManager.GetString("MasterImage", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mosaic.
        /// </summary>
        public static string Mosaic {
            get {
                return ResourceManager.GetString("Mosaic", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PNG image.
        /// </summary>
        public static string PNGPicture {
            get {
                return ResourceManager.GetString("PNGPicture", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Print preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Filling main picture.
        /// </summary>
        public static string Randomizing {
            get {
                return ResourceManager.GetString("Randomizing", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Random tiles.
        /// </summary>
        public static string RandomPlacedTiles {
            get {
                return ResourceManager.GetString("RandomPlacedTiles", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This is ratio of longer edge of main picture to longer edge of tile..
        /// </summary>
        public static string RatioExplanation {
            get {
                return ResourceManager.GetString("RatioExplanation", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rescale.
        /// </summary>
        public static string Rescale {
            get {
                return ResourceManager.GetString("Rescale", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu It&apos;s not possible to use main image as tile. Do you want to make a copy of and use it as tile?.
        /// </summary>
        public static string SamePictureFound {
            get {
                return ResourceManager.GetString("SamePictureFound", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save picture.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save project.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Procedure terminated by user..
        /// </summary>
        public static string TerminatedByUser {
            get {
                return ResourceManager.GetString("TerminatedByUser", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tiles in group.
        /// </summary>
        public static string TilesInGroup {
            get {
                return ResourceManager.GetString("TilesInGroup", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tiles randomize.
        /// </summary>
        public static string TilesRandomize {
            get {
                return ResourceManager.GetString("TilesRandomize", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Will be in future.
        /// </summary>
        public static string WillBeInFuture {
            get {
                return ResourceManager.GetString("WillBeInFuture", resourceCulture);
            }
        }
    }
}
