//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("i18n.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Aboutbox {
            get {
                return ResourceManager.GetString("Aboutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least you have to add 15 tiles..
        /// </summary>
        public static string AddAtLeast15Tiles {
            get {
                return ResourceManager.GetString("AddAtLeast15Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hue to each tile.
        /// </summary>
        public static string AddHue {
            get {
                return ResourceManager.GetString("AddHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to add some tiles first..
        /// </summary>
        public static string AddTilesFirst {
            get {
                return ResourceManager.GetString("AddTilesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust tile hue.
        /// </summary>
        public static string AdjustHue {
            get {
                return ResourceManager.GetString("AdjustHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging Master Bitmap....
        /// </summary>
        public static string AveragingMasterBitmap {
            get {
                return ResourceManager.GetString("AveragingMasterBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap.
        /// </summary>
        public static string Bitmap {
            get {
                return ResourceManager.GetString("Bitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        public static string Buffer {
            get {
                return ResourceManager.GetString("Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m calculating mosaic. This may take a while....
        /// </summary>
        public static string CalculateMosaic {
            get {
                return ResourceManager.GetString("CalculateMosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color tiles.
        /// </summary>
        public static string ColorPlacedTiles {
            get {
                return ResourceManager.GetString("ColorPlacedTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors calculated..
        /// </summary>
        public static string ColorsCalculated {
            get {
                return ResourceManager.GetString("ColorsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF image.
        /// </summary>
        public static string GIFPicture {
            get {
                return ResourceManager.GetString("GIFPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and Resizing Tile Images....
        /// </summary>
        public static string LoadingAndResizingTiles {
            get {
                return ResourceManager.GetString("LoadingAndResizingTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maser file....
        /// </summary>
        public static string LoadingMasterFile {
            get {
                return ResourceManager.GetString("LoadingMasterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master image.
        /// </summary>
        public static string MasterImage {
            get {
                return ResourceManager.GetString("MasterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic.
        /// </summary>
        public static string Mosaic {
            get {
                return ResourceManager.GetString("Mosaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG image.
        /// </summary>
        public static string PNGPicture {
            get {
                return ResourceManager.GetString("PNGPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling main picture.
        /// </summary>
        public static string Randomizing {
            get {
                return ResourceManager.GetString("Randomizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random tiles.
        /// </summary>
        public static string RandomPlacedTiles {
            get {
                return ResourceManager.GetString("RandomPlacedTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is ratio of longer edge of main picture to longer edge of tile..
        /// </summary>
        public static string RatioExplanation {
            get {
                return ResourceManager.GetString("RatioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescale.
        /// </summary>
        public static string Rescale {
            get {
                return ResourceManager.GetString("Rescale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to use main image as tile. Do you want to make a copy of and use it as tile?.
        /// </summary>
        public static string SamePictureFound {
            get {
                return ResourceManager.GetString("SamePictureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save picture.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure terminated by user..
        /// </summary>
        public static string TerminatedByUser {
            get {
                return ResourceManager.GetString("TerminatedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles in group.
        /// </summary>
        public static string TilesInGroup {
            get {
                return ResourceManager.GetString("TilesInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles randomize.
        /// </summary>
        public static string TilesRandomize {
            get {
                return ResourceManager.GetString("TilesRandomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be in future.
        /// </summary>
        public static string WillBeInFuture {
            get {
                return ResourceManager.GetString("WillBeInFuture", resourceCulture);
            }
        }
    }
}
